//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DefenseTimoEntities : DbContext
    {
        public DefenseTimoEntities()
            : base("name=DefenseTimoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Eleve> Eleves { get; set; }
        public virtual DbSet<Frai> Frais { get; set; }
        public virtual DbSet<Mois> Mois { get; set; }
        public virtual DbSet<Paye> Payes { get; set; }
        public virtual DbSet<Recu> Recus { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<ViewLignePayement> ViewLignePayements { get; set; }
        public virtual DbSet<ViewTotalMoisParEleveTou> ViewTotalMoisParEleveTous { get; set; }
        public virtual DbSet<ViewTotalParEleve> ViewTotalParEleves { get; set; }
    
        public virtual ObjectResult<ProcLignePayement_Result> ProcLignePayement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcLignePayement_Result>("ProcLignePayement");
        }
    
        public virtual ObjectResult<ProcTotalMoisParEleveTous_Result> ProcTotalMoisParEleveTous()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcTotalMoisParEleveTous_Result>("ProcTotalMoisParEleveTous");
        }
    
        public virtual ObjectResult<Nullable<int>> ProcNumeroRecu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ProcNumeroRecu");
        }
    }
}
