//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paye
    {
        public int ID { get; set; }
        public string MatriculeEl { get; set; }
        public string NumFrais { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public Nullable<System.DateTime> DatePaye { get; set; }
        public string CodeMois { get; set; }
    
        public virtual Eleve Eleve { get; set; }
        public virtual Frai Frai { get; set; }
        public virtual Mois Mois1 { get; set; }
    }
}
