//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recu
    {
        public int NumRecu { get; set; }
        public string Motif { get; set; }
        public Nullable<System.DateTime> DateRecu { get; set; }
        public string MatriculeEl { get; set; }
    
        public virtual Eleve Eleve { get; set; }
    }
}
