//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLignePayement
    {
        public string MatriculeEl { get; set; }
        public string Nom { get; set; }
        public string PostNom { get; set; }
        public string Prenom { get; set; }
        public string Classe { get; set; }
        public Nullable<System.DateTime> DatePaye { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string LibelleMois { get; set; }
    }
}
